In [1]:
import Diference_Categorical
import numpy as np

# From Data

params = {
    "Column 1": np.array([1,2,3,4,3,2,1,3,5,4,3,2,2,2,1,2,1,2,3,2,1,1]), 
    "Column 2": np.array([2,2,2,2,2,3,3,3,3,3,4,4,4,4,4,5,5,5,5,5,5,5]),
    "Column 3": np.array([1,2,3,4,3,2,1,3,5,4,1,1,1,1,1,2,3,2,1,1,1,1]), 
    "Column 4": np.array([2,1,2,3,2,1,4,5,3,4,4,4,4,4,3,2,1,2,1,2,2,2]), 
    "Confidence Level": 95
}

# Call the function
results = Diference_Categorical.Categorical_Association_Difference.Categorical_Association_difference_from_data(params)


# Print the results
print("Results of Nominal by Nominal from Data:")
for key, value in results.items():
    print(f"{key}: {value}")

print()

[[1 1 1 3]
 [1 1 3 3]
 [2 1 1 1]
 [1 1 0 0]
 [0 1 0 0]]
[[1 4 1 5 0]
 [2 2 0 0 0]
 [1 2 0 0 1]
 [0 0 1 1 0]
 [0 0 1 0 0]]
Results of Nominal by Nominal from Data:
Lambda Rows 1: 0.2
Lambda Rows 2: 0.2142857
p-value Lambda Rows 1: 0.9331927987311419
p-value Lambda Rows 2: 0.8462429320162892
Difference Between Lambda Rows: -0.014285699999999985
Standard Error of the Difference Rows: 0.18856176117596057
Z-Statistic of the Difference Rows: -0.05743114408072828
p-value Rows: 0.9542017545475352
Lambda Columns 1: 0.0714286
Lambda Columns 2: 0.1818182
p-value Lambda Columns 1: 0.7254617986438179
p-value Lambda Columns 2: 0.8655375097441902
Difference Between Lambda Columns: -0.11038960000000002
Standard Error of the Difference Columns: 0.16859914679357071
Z-Statistic of the Difference Columns: -0.5434539082637428
p-value Columns: 0.5868173175811258
Lambda Symmetric 1: 0.137931
Lambda Symmetric 2: 0.2
p-value Lambda Symmetric 1: 0.7828511715174633
p-value Lambda Symmetric 2: 0.8745751606328258
