In [ ]:
import Multiple_R_Square
import numpy as np
import pandas as pd

# From Data

params = {
    "Data": pd.DataFrame({
        "Predicted": [1, 2, 3, 4, 3, 2, 1, 3, 5, 4, 3, 2, 2, 2, 1, 2, 1, 2, 3, 2, 1, 1],
        "x1": [2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5],
        "x2": [1, 2, 3, 4, 3, 2, 1, 3, 5, 4, 1, 1, 1, 1, 1, 2, 3, 2, 1, 1, 1, 1],
        "x3": [2, 1, 2, 3, 2, 1, 4, 5, 3, 4, 4, 4, 4, 4, 3, 2, 1, 2, 1, 2, 2, 2]
    }),
    "Confidence Level": 95
}

# Call the function
results = Multiple_R_Square.R_Squared.R_Squared_From_Data(params)


# Print the results
print("Results of R Sqared From Data:")
for key, value in results.items():
    print(f"{key}: {value}")

print()

Results of R Sqared From Data:
Predictor: [[2 1 2]
 [2 2 1]
 [2 3 2]
 [2 4 3]
 [2 3 2]
 [3 2 1]
 [3 1 4]
 [3 3 5]
 [3 5 3]
 [3 4 4]
 [4 1 4]
 [4 1 4]
 [4 1 4]
 [4 1 4]
 [4 1 3]
 [5 2 2]
 [5 3 1]
 [5 2 2]
 [5 1 1]
 [5 1 2]
 [5 1 2]
 [5 1 2]]

